services:
  - type: web
    name: elon-digital-twin
    runtime: python
    buildCommand: |
      pip install poetry
      poetry install --no-dev
    startCommand: poetry run uvicorn server:server --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        sync: false

      - key: GROQ_API_KEY_1
        sync: false
      - key: GROQ_API_KEY_2
        sync: false
      - key: GROQ_API_KEY_3
        sync: false

      - key: TAVILY_API_KEY_1
        sync: false
      - key: TAVILY_API_KEY_2
        sync: false
      - key: TAVILY_API_KEY_3
        sync: false
